odometry_mode: 1

lidar_yaml: /geoscan_s1/lidar.yaml
imu_yaml: /geoscan_s1/imu.yaml
# camera_yaml: /geoscan_s1/camera.yaml # Their calibration results shared on MS teams on Feb 19th, 2026
camera_yaml: /geoscan_s1/camera_ours.yaml # Our own calibration results

# Our own rosbag
# bag_path: /home/Documents/real2sim2real/warehouse/ours_rosbag/data_single.bag
# bag_path: /home/Documents/real2sim2real/warehouse/ours_rosbag/data_single_lab.bag
# bag_path: /home/Documents/real2sim2real/warehouse/ours_rosbag/data_single_office.bag
# bag_path: /home/Documents/real2sim2real/warehouse/ours_rosbag/data_single_officedesk.bag
# bag_path: /home/Documents/real2sim2real/warehouse/ours_rosbag/data_single_labtable.bag
bag_path: /home/Documents/real2sim2real/warehouse/ours_rosbag/data_single_labrandom.bag
# bag_path: /home/Documents/real2sim2real/warehouse/ours_rosbag/data_single_kukararm.bag
# bag_path: /home/Documents/real2sim2real/warehouse/ours_rosbag/data_single_officedesk_static.bag
# bag_path: /home/Documents/real2sim2real/warehouse/ours_rosbag/data_single_officedesk_static_2.bag

# Their rosbag
# bag_path: /home/Documents/real2sim2real/warehouse/their_rosbag/2026-02-05-15-12-33.bag # static
# bag_path: /home/Documents/real2sim2real/warehouse/their_rosbag/2026-02-05-15-59-14.bag # move

bag_start: 0.
bag_durr: -1

t_add: 0.1
distance0: 0.03
non_uniform: true
division_coarse: 1

t_begin_add_cam: 1.0
lidar_iter: 2
use_lidar_scale: true
lidar_weight: 500.0
image_weight: 4.0
gyroscope_noise_density: 8.0226069504443656e-04
gyroscope_random_walk: 4.4153147263889589e-05
accelerometer_noise_density: 1.0909715156015328e-02
accelerometer_random_walk: 4.0347767978459928e-04

is_evo_viral: false

if_3dgs: true
lidar_skip: 10
